int schedule();
int init();
int create(char* PID, int priority);
int destroy(char* PID);
int rfree(inode* p);
int request(char* RID, int n);
int release(inode* proc,char* RID, int n);
int time_out();
int judgeSpace(char* str);
int test_shell();
int list_insert(inode* list,inode* node);
int list_delete(inode* list,char *PID);
int judgeSpace(char* str);
int disp_ready();
int disp_block();
int disp_resource();
int show_rela();
int kill_tree(char *PID);