int schedule();
int init();
int create(char* PID, char priority);
int destroy(char* PID);
int rfree(inode* p);
int request(char* RID, int n);
int release(inode* proc,char* RID, int n);
int time_out();
int judgeSpace(char* str);
int test_shell();
int list_insert(inode* list,inode* node);
inode* list_delete(inode* list,char *PID);